### ISSUE TITLE
Apache 2.0 in earlier versions

### ISSUE THREAD

**Issue by spectejb** [jsdom/xml-name-validator#5]
Hello!  Would you mind updating the license file in the earlier versions from WTFPL to Apache 2.0?  That would be very helpful!  Thank you, in advance, for your help!

**Comment by spectejb** [comment]
Hey @domenic , @Zirro , @Sebmaster @TimothyGu , @jeffcarp - I am just following up on this request.   Really appreciate your help on this!

**Comment by domenic** [comment]
Old versions are already published and cannot be changed.

**Comment by spectejb** [comment]
Thanks for your response, @domenic.  I will see what the team can do about upgrading to the most recent version if an update to the past versions is unavailable..
